const foodsData = [
  {
    name: "Hummus",
    typeOfFood: "Dip",
    temperature: "Cold",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Falafel",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Shawarma",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Sushi",
    typeOfFood: "Dinner",
    temperature: "Cold",
    FlavorProfile: "Umami",
    region: "Japan",
  },
  {
    name: "Pizza",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Italy",
  },
  {
    name: "Tacos",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Spicy",
    region: "Mexico",
  },
  {
    name: "Paella",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Spain",
  },
  {
    name: "Ramen",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Umami",
    region: "Japan",
  },
  {
    name: "Kimchi",
    typeOfFood: "Side",
    temperature: "Cold",
    FlavorProfile: "Spicy",
    region: "Korea",
  },
  {
    name: "Biryani",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Spicy",
    region: "India",
  },
  {
    name: "Goulash",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Hungary",
  },
  {
    name: "Pho",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Vietnam",
  },
  {
    name: "Dumplings",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "China",
  },
  {
    name: "Poutine",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Canada",
  },
  {
    name: "Tiramisu",
    typeOfFood: "Dessert",
    temperature: "Cold",
    FlavorProfile: "Sweet",
    region: "Italy",
  },
  {
    name: "Baklava",
    typeOfFood: "Dessert",
    temperature: "Room",
    FlavorProfile: "Sweet",
    region: "Middle East",
  },
  {
    name: "Arepas",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Colombia",
  },
  {
    name: "Empanadas",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Latin America",
  },
  {
    name: "Borscht",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Russia",
  },
  {
    name: "Pierogi",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Poland",
  },
  {
    name: "Bibimbap",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Korea",
  },
  {
    name: "Dimsum",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "China",
  },
  {
    name: "Padthai",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Sweet",
    region: "Thailand",
  },
  {
    name: "Risotto",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Italy",
  },
  {
    name: "Gyoza",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Japan",
  },
  {
    name: "Mochi",
    typeOfFood: "Dessert",
    temperature: "Cold",
    FlavorProfile: "Sweet",
    region: "Japan",
  },
  {
    name: "Churros",
    typeOfFood: "Dessert",
    temperature: "Hot",
    FlavorProfile: "Sweet",
    region: "Spain",
  },
  {
    name: "Gazpacho",
    typeOfFood: "Appetizer",
    temperature: "Cold",
    FlavorProfile: "Fresh",
    region: "Spain",
  },
  {
    name: "Fondue",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Switzerland",
  },
  {
    name: "Ceviche",
    typeOfFood: "Appetizer",
    temperature: "Cold",
    FlavorProfile: "Fresh",
    region: "Peru",
  },
  {
    name: "Kebab",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Tabbouleh",
    typeOfFood: "Salad",
    temperature: "Cold",
    FlavorProfile: "Fresh",
    region: "Middle East",
  },
  {
    name: "Shakshuka",
    typeOfFood: "Breakfast",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Mansaf",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Kunafa",
    typeOfFood: "Dessert",
    temperature: "Hot",
    FlavorProfile: "Sweet",
    region: "Middle East",
  },
  {
    name: "Molokhia",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Harissa",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Spicy",
    region: "Tunisia",
  },
  {
    name: "Fatteh",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Manakish",
    typeOfFood: "Breakfast",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Labneh",
    typeOfFood: "Dip",
    temperature: "Cold",
    FlavorProfile: "Tangy",
    region: "Middle East",
  },
  {
    name: "Koshari",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Egypt",
  },
  {
    name: "Sambousek",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Kibbeh",
    typeOfFood: "Snack",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Basbousa",
    typeOfFood: "Dessert",
    temperature: "Room",
    FlavorProfile: "Sweet",
    region: "Middle East",
  },
  {
    name: "Fesenjan",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Sweet",
    region: "Iran",
  },
  {
    name: "Ghormeh",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Iran",
  },
  {
    name: "Bamia",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Middle East",
  },
  {
    name: "Pastilla",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Sweet",
    region: "Morocco",
  },
  {
    name: "Couscous",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "North Africa",
  },
  {
    name: "Tagine",
    typeOfFood: "Dinner",
    temperature: "Hot",
    FlavorProfile: "Savory",
    region: "Morocco",
  },
];
  export default foodsData;